pipeline {
    agent none
    parameters {
        string(
            description: 'Input mysql root password.',
            name: 'MYSQL_ROOT_PASSWORD',
            defaultValue: '123456',
        )
        string(
            description: 'Input artifactory user name.',
            name: 'ARTIFACTORY_USER',
            defaultValue: 'zenops-user',
        )
        string(
            description: 'Input artifactory user password.',
            name: 'ARTIFACTORY_PASSWORD',
            defaultValue: 'P2ssw0rd',
        )
    }
    stages {
        stage('start builder container to compile and package') {
            agent { node { label 'build-server' } }
            steps {
                echo 'start to compile'

                sh 'docker pull 192.168.1.161:59082/zenops/zentao-builder:latest'
                sh 'docker rm -f zentao-builder'
                sh 'docker run -d --name zentao-builder 192.168.1.161:59082/zenops/zentao-builder:latest'
            }
        },
	    stage('build image') {
	    	agent { node { label 'build-server' } }
		    steps {
		    	dir ('zentao/run') {
			        script {
			            echo 'load config'
			            sh 'wget http://192.168.1.161:58082/artifactory/zentaopms/config/config.zip'
			            sh 'unzip -o config.zip -d config'

			            echo 'build docker image ...'
			            sh 'docker build \
			                --build-arg MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} \
			                --rm -t 192.168.1.161:59082/zenops/zentao-server:latest .'
			        }
		        }
		    }
	    }
	    stage('push image') {
            agent { node { label 'build-server' } }
                steps {
                    echo 'upload docker image ...'

                    sh 'docker login -u ${ARTIFACTORY_USER} -p ${ARTIFACTORY_PASSWORD} 192.168.1.161:59082'
                    sh 'docker push 192.168.1.161:59082/zenops/zentao-server:latest'
                }
            }
	    stage('start container') {
		    agent { node { label 'build-server' } }
			steps {
                echo 'start container'

                sh 'docker pull 192.168.1.161:59082/zenops/zentao-server:latest'
                sh 'docker rm -f zentao-server'
                sh 'docker run -d --name zentao-server \
                        -p 50001:80 \
                        192.168.1.161:59082/zenops/zentao-server:latest'
			}
	    }
	}
}
